variables:
  SCALENODE_RAM: 8192

stages:
  - build
  - doc-deploy
  - ui-tests
  - deploy

build:
  stage: build
  image: node:22
  variables:
    NODE_OPTIONS: "--max-old-space-size=4096"
  before_script:
    - npm ci
  script:
    - npm run check-format
    - npm run build
  artifacts:
    paths:
      - dist

functional-tests:
  stage: ui-tests
  image: node:22
  dependencies: [build]
  before_script:
    - npm ci
  script:
    - ./tests/test-server.sh
    - npx playwright install --with-deps chromium
    - npm run test
  artifacts:
    when: always
    paths:
      - test-results
      - playwright-report/index.html
  variables:
    SCALENODE_CPU: 8

build-docs:
  stage: build
  when: manual
  image: $CI_DOCS_DOCKER_IMAGE
  tags: ["ace-x86_64"]
  before_get_sources:
    - apt-get update
    - apt-get install python3-venv python3-pip python3 -y
  before_script:
    - cd docs
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - cd docs
    - source .venv/bin/activate
    - |
      printf "\nfrom antmicro_sphinx_utils.defaults import relative_to_git\nfrom pathlib import Path\ngit_path = relative_to_git(Path(__file__).parent)\nhtml_css_files = ['$MYST_LOADER_REPOSITORY/MystEditor.css']\nhtml_js_files = [(f'$MYST_LOADER_REPOSITORY/myst_loader.js?fix=://&docs-root={str(git_path).replace(\"/\", \"%%2F\")}', { 'type': 'module' })]" >> source/conf.py
    - make html
    - cd ..
    - tar cf $CI_DOCS_ARCHIVE -C docs/build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

doc-deploy:
  stage: doc-deploy
  image: node:22
  tags: ["docs"]
  dependencies: [build]
  script:
    - sed -i -e 's/{}.VITE_COLLAB/"ON"/g' dist/index.js
    - sed -i -e 's/{}.VITE_WS_URL/"\/devsignal"/g' dist/index.js
    - tar cf $CI_DOCS_ARCHIVE -C dist/ .
  artifacts:
    paths:
      - docs.tar
  only:
    - merge_requests

deploy-docs:
  stage: deploy
  when: manual
  tags: ["docs"]
  image: $CI_DOCS_DOCKER_IMAGE
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build-docs
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
